### ISSUE TITLE
Put lineups display different effects from existing data in json file

### ISSUE THREAD

**Issue by FYimu** [AY2122S2-CS2103-F09-1/tp#138]
The process to test:
1. Run Main.java
2. `add L/ n/Starting 5`
3. `put P/Alex Yeoh L/Starting 5`
4. `view L/` -> displays all players with lineups
5. `view P/` -> displays all players only, but Alex Yeoh will still have lineup `Starting 5` shown

**Comment by DALIN-Prog** [comment]
Resolved
