### ISSUE TITLE
[PE-D] Invalid date when creating a schedule does not throw an exception

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-1/tp#196]
## Summary
Adding a schedule event with 31 February does not throw an error, and creates an event on 29 February. The user does not know that 31 February is not allowed, or that an event with a different date is created instead.

## Screenshot
Input:
![image.png](https://raw.githubusercontent.com/sbhbenjamin/ped/main/files/4c145033-80c4-481e-a2fa-9a454a2a6fb8.png)

Result:
![image.png](https://raw.githubusercontent.com/sbhbenjamin/ped/main/files/5e426be2-84e2-4a9d-82e1-3dc62f0aa5e9.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sbhbenjamin/ped#5

**Comment by DALIN-Prog** [comment]
duplicate #233
