### ISSUE TITLE
[PE-D] Duplicate player name in result display of lineup

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-1/tp#204]
![image.png](https://raw.githubusercontent.com/chriswengqi/ped/main/files/eaf83fe9-42c9-4b2e-aa66-ffb13b633b6a.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: chriswengqi/ped#1

**Comment by FYimu** [comment]
Cannot replicate the issue.
