### ISSUE TITLE
[PE-D] Calendar not updated after adding in Schedules

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-1/tp#219]
![image.png](https://raw.githubusercontent.com/chriswengqi/ped/main/files/af1f6b81-7bce-46fb-84ce-c7e0c159da9d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chriswengqi/ped#7

**Comment by snoidetx** [comment]
This issue cannot be replicated.
