### ISSUE TITLE
[PE-D] When switching themes, the image is cut off

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-1/tp#231]
## Summary
On windows, when switching between themes through `theme T/light` and `theme T/dark`, the image gets cut off.

## Screenshot
![image.png](https://raw.githubusercontent.com/sbhbenjamin/ped/main/files/64aab863-1426-4188-9858-586eba50d953.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sbhbenjamin/ped#11

**Comment by DALIN-Prog** [comment]
Dual monitor issue
