### ISSUE TITLE
[PE-D] Inconsistency between documentation and application for editing a player's tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F09-1/tp#235]
## Summary
The documentation mentions that editing a player can be done with the syntax `[T/TAGS]`, however, when this is input in the application, it is invalid. Is this a typo where it is supposed to be `[t/TAG]`?

## Screenshot
Documentation:
![image.png](https://raw.githubusercontent.com/sbhbenjamin/ped/main/files/c106f064-bdee-49a5-bb88-5d7705390a9a.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: sbhbenjamin/ped#15

**Comment by DALIN-Prog** [comment]
duplicate #237
